# Generated by Django 4.1.1 on 2022-10-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_alter_contributor_role_alter_issue_assignee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_user_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='issue',
            new_name='issue_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='assignee',
            new_name='assignee_user_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='author',
            new_name='author_user_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='project',
            new_name='project_id',
        ),
    ]
